---
format_version: 10
pipelines:
  docker-rebuild:
    group: dockerTaskRebuild
    materials:
      gitrepo:
        git: https://github.com/baugistoms/ui-automation.git
        branch: main
    stages:
      - build-ubuntu-jdk-mvn:
          jobs:
            build:
              tasks:
               - exec:
                    command: bash
                    arguments:
                      - -c
                      - docker build -t ubuntu-jdk-mvn . -f Dockerfile
      - build-mvn-tests:
          jobs:
            build:
              tasks:
               - exec:
                    command: bash
                    arguments:
                      - -c
                      - docker build -t baugist/mvn_tests:latest . -f Dockerfile_tests
               - exec:
                    command: bash
                    arguments:
                      - -c
                      - docker push baugist/mvn_tests:latest